CREATE TABLE "APP"."ARTICLE" (
 CODE varchar(5) PRIMARY KEY NOT NULL,
 NOM varchar(32) NOT NULL,
 PRIX float(52) NOT NULL );

CREATE TABLE "APP"."COMMANDE" (
 ID int PRIMARY KEY NOT NULL,
 IDUTILISATEUR int NOT NULL,
 FLAG int DEFAULT 0 NOT NULL );

CREATE TABLE "APP"."LISTECOMMANDE" (
 IDCOMMANDE int NOT NULL,
 CODEARTICLE varchar(5) NOT NULL,
 QUANTITE int NOT NULL );

CREATE TABLE "APP"."PAYS"(
 ID int PRIMARY KEY NOT NULL,
 NOM varchar(32) NOT NULL );

CREATE TABLE "APP"."UTILISATEUR" (
 ID int PRIMARY KEY NOT NULL,
 LOGIN varchar(32) NOT NULL,
 PASSWORD varchar(32) NOT NULL,
 NOM varchar(32) NOT NULL,
 PRENOM varchar(32) NOT NULL,
 ADRESSE varchar(64) NOT NULL,
 CODEPOSTAL varchar(6) NOT NULL,
 VILLE varchar(32) NOT NULL,
 IDPAYS int NOT NULL );


CREATE UNIQUE INDEX UNIQUE_ARTICLE_CODE ON "APP"."ARTICLE"(CODE);

ALTER TABLE "APP"."COMMANDE" ADD CONSTRAINT FK_UTILISATEUR_ID FOREIGN KEY (IDUTILISATEUR) REFERENCES "APP"."UTILISATEUR"(ID);
CREATE UNIQUE INDEX UNIQUE_COMMANDE_ID ON "APP"."COMMANDE"(ID);
CREATE INDEX INDEX_COMMANDE_UTILISATEUR ON "APP"."COMMANDE"(IDUTILISATEUR);


ALTER TABLE "APP"."LISTECOMMANDE" ADD CONSTRAINT PK_IDC_CODEA PRIMARY KEY (IDCOMMANDE, CODEARTICLE);
ALTER TABLE "APP"."LISTECOMMANDE" ADD CONSTRAINT FK_ARTICLE_CODE FOREIGN KEY (CODEARTICLE) REFERENCES "APP"."ARTICLE"(CODE);
ALTER TABLE "APP"."LISTECOMMANDE" ADD CONSTRAINT FK_COMMANDE_ID FOREIGN KEY (IDCOMMANDE) REFERENCES "APP"."COMMANDE"(ID);
CREATE UNIQUE INDEX UNIQUE_LISTECOMMANDE_IDCOMMANDE ON "APP"."LISTECOMMANDE"(IDCOMMANDE);
CREATE INDEX INDEX_LISTECOMMANDE_IDCOMMANDE ON "APP"."LISTECOMMANDE"(IDCOMMANDE);
CREATE INDEX INDEX_LISTECOMMANDE_CODEARTICLE ON "APP"."LISTECOMMANDE"(CODEARTICLE);

CREATE UNIQUE INDEX UNIQUE_PAYSID ON "APP"."PAYS"(ID);

ALTER TABLE "APP"."UTILISATEUR" ADD CONSTRAINT FK_PAYS_ID FOREIGN KEY (IDPAYS) REFERENCES "APP"."PAYS"(ID);
CREATE UNIQUE INDEX UNIQUE_UTILISATEUR_ID ON "APP"."UTILISATEUR"(ID);
CREATE INDEX INDEX_UTILISATEUR_IDPAYS ON "APP"."UTILISATEUR"(IDPAYS);


INSERT INTO APP.ARTICLE VALUES ('REF01', 'Tondeuse gazon', 199.99);
INSERT INTO APP.ARTICLE VALUES ('REF02', 'Ecran 24 pouces', 139.99);
INSERT INTO APP.ARTICLE VALUES ('REF03', 'Cadre photo', 9.99);
INSERT INTO APP.ARTICLE VALUES ('REF04', 'Enceintes Altec 2.1 28W', 39.99);
INSERT INTO APP.ARTICLE VALUES ('REF05', 'XBOX 360 Slim', 199.99);

INSERT INTO APP.PAYS VALUES(1, 'France');
INSERT INTO APP.PAYS VALUES(2, 'Espagne');
INSERT INTO APP.PAYS VALUES(3, 'Allemagne');

INSERT INTO APP.UTILISATEUR VALUES (1, 'lilaA', 'pass', 'Lila', 'Aona', '20 plaza real', '28001', 'MADRID', 2);
INSERT INTO APP.UTILISATEUR VALUES (2, 'maxD', 'pass', 'Max', 'DOULA', '36 route de la boustipaille', '75000', 'PARIS', 1);
INSERT INTO APP.UTILISATEUR VALUES (3, 'laurentJ', 'pass', 'Laurent', 'JEODU', '36 route de la boustipaille', '75000', 'PARIS', 1);